### ISSUE TITLE
Where is the boolean decision on whether an item was answered correctly by a subject being made?

### ISSUE THREAD

**Issue by pk1130** [facebookresearch/irt-leaderboard#1]
Hey @EntilZha! I saw that you'd said that instance-level test-scores of SQuAD models cannot be released to maintain the integrity of the benchmark tests. For the purposes of our research, we wanted to understand where the boolean decision on whether a SQuAD model answered a question/item correctly is located. Is that publicly available information? If yes, could you please point me in that direction? 

I took a look at the `leaderboard/` directory, specifically in the `codalab.py` file and saw the `compute_pred_scores()` function. In this function, I saw that the `pred_file` was a `json` file located in `data/squad/submissions/submit_id.json`. If my understanding is right, this `json` is of the form:
```
{
   subject_id: ........., 
   name: ........, 
   responses: { 
          id_1: 0, 
          id_2: 1, 
          id_3: 1, 
          .............
   } 
}
```

My exact question is "where exactly is the boolean decision that subject_id `xxxxxx` answered item with `id_1` correctly/incorrectly being made?"

Please respond at your earliest convenience. Thanks in advance!

**Comment by EntilZha** [comment]
You should be able to download that data file for the dev set, it's the same file for the test data that I couldn't provide.

Isn't that decision being made within the `compute_pred_scores` function, specifically `get_raw_scores`?
https://github.com/facebookresearch/irt-leaderboard/blob/597a4f60f680c125a7f30a32af22af0daa1838d1/leaderboard/squad_eval_v2.py#L114

**Comment by pk1130** [comment]
Thanks for pointing me to that file @EntilZha! On probing further, I found exactly where the boolean decision is being made. It is being made inside here:

https://github.com/facebookresearch/irt-leaderboard/blob/597a4f60f680c125a7f30a32af22af0daa1838d1/leaderboard/squad_eval_v2.py#L60

More specifically, in this line inside this function:
https://github.com/facebookresearch/irt-leaderboard/blob/597a4f60f680c125a7f30a32af22af0daa1838d1/leaderboard/squad_eval_v2.py#L65

I think the `get_raw_scores()` function is computing the metrics for the predictions and not whether the model got that question correct/incorrect right? Please do correct me if my understanding is wrong! Thanks once again!

**Comment by EntilZha** [comment]
I'm not sure I understand the difference you mean by computing metrics for predictions and whether the model got the question got it correct. Aren't they the same?

For this paper, questions were current if the exact match score is 1. While there are IRT formulations for float/double scores, they aren't as standard as integer scoring (or in this case 1/0 scoring).

**Comment by pk1130** [comment]
I was thinking that computing metrics involved looking at all the questions that a particular model has predicted on and calculating accuracy/precision/recall/f1-scores, whereas whether a model got a particular question correct is an integer score of 0/1. Am I understanding this incorrectly?

So, in this case, for example, computing the precision of a particular model like RAG would involve looking at all the questions that the model has predicted on, calculate how many questions the model has predicted correctly on (gotten the question right; in other words, a true positive) and divide that by the true positives and false positives. Am I right?

**Comment by EntilZha** [comment]
The way that SQUaD evaluation works, is that they compute an Exact Match and token F1 score for each question. Then, these scores are averaged across all questions to give the EM/F1 scores you see in papers. This function obtains the EM/F1 scores for each question, but does not aggregate them. For the ACL paper, I basically said a model gets a question correct if EM=1

**Comment by pk1130** [comment]
Oh ok, that makes a lot more sense! Thanks for the clarification!
